version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pjc_hr
      MYSQL_USER: pjc
      MYSQL_PASSWORD: pjc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pjc_hr?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: pjc
      SPRING_DATASOURCE_PASSWORD: pjc
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
